# elementary OS Travis UNSTABLE
FROM elementary/docker:loki-unstable

MAINTAINER Cody Garver <cody@elementary.io>

COPY install-dependencies-and-cmake-make install-dependencies-and-cmake-make-all-test /usr/local/bin/

RUN chmod +x /usr/local/bin/install-dependencies-and-cmake-make /usr/local/bin/install-dependencies-and-cmake-make-all-test
